version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.9.0
      - image: circleci/mongo:3.4.4
    working_directory: ~/frodocms
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: install-globals
          command: npm install -g gulp karma
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: build
          command: ./node_modules/gulp/bin/gulp.js build
      - run:
          name: test
          command: npm run test
      - run:
          name: start
          command: npm start
